### ISSUE TITLE
Spaces in Windows Path

### ISSUE THREAD

**Issue by jonszcz** [noseglid/atom-build#320]
I'm struggling to get my build to complete on a Windows machine. The path keeps breaking due to a space in the filenames. I initially thought my problem was similar to Issue #189, but the windows CMD seems to want to use double quotes to denote a path with spaces. So the resolution in that issue doesn't want to work for me here. 

This build does work on my mac, but not windows. Any thoughts on either a) how to include a double quote in the file path, or restructuring my arguments differently for this build?

Here is a copy of my current .atom-build.yml
```YAML
cmd: pandoc
name: 'Markdown to HTML'
sh: true
args: [-c "'/notebook/BCJ Styling.css'", -f markdown+hard_line_breaks, -t html5, "'{FILE_ACTIVE}'", -o $out ]
env: {
     out: "'{FILE_ACTIVE}.html'",
 }
```
In the locations where I'm including a path, I'm using the single quotes so that it builds on the mac side. In the build panel, the paths are showing as enclosed with single quotes, but as I mentioned, cmd.exe doesn't like this.
