### ISSUE TITLE
F7 shows no targets names

### ISSUE THREAD

**Issue by Heather** [noseglid/atom-build#377]
F7 shows no targets names, it just shows `"Custom 1"`, `"Custom 2"`, ...

and by default (when no target is selected) it can't pick default target ...

config:

``` yaml
targets:
  - install:
    cmd: cabal
    args:
     - install
     - --force-reinstall
    name: cabal install
  - test:
    cmd: shake
    args:
      - -f
    name: test
```

**Comment by noseglid** [comment]
That's because you're defining an array. Try this:
```
targets:
  install:
    cmd: cabal
    args:
     - install
     - --force-reinstall
    name: cabal install
  test:
    cmd: shake
    args:
      - -f
    name: test
```
