### ISSUE TITLE
Custom variables

### ISSUE THREAD

**Issue by trianglesis** [noseglid/atom-build#530]
Hi,
Is there any chance to use custom variables in yml?

Like:
```
variables:
  PYTHON27: '${C:\\Python27\\python.exe}'
  PYTHON34: "{{C:\\Python34\\python.exe}}"
```

And then you can use each in whole build:

`cmd: '{PYTHON27}'`

Or sometthing.
Reading yaml documentation - it gives some examples of that. But nothing worked in this case.

Thanks,

**Comment by triaglesis** [comment]
Some buggy workaround:

https://stackoverflow.com/questions/5484016/how-can-i-do-string-concatenation-or-string-replacement-in-yaml

```
PYTHON27: &PYTHON27 C:\Python27\python.exe
CHECK: &CHECK "C:\\Python34\\python.exe D:\\TPL_IDE_Module\\check_active\\check.py"
```
Working example:

```
cmd: *PYTHON27
args:
  - *PREPROC
  - '-f {FILE_ACTIVE}'

```
AND

```
  - tplpreSyntaxCheckSolo:
    cmd: *CHECK
    args:
      - '-full_path {FILE_ACTIVE}'
      - '-l info'
    cwd: '{FILE_ACTIVE_PATH}'
```
