### ISSUE TITLE
how do i get the colors in the output?

### ISSUE THREAD

**Issue by RamyRais** [noseglid/atom-build#544]
i have this simple configuration that is running a gulp task
```
targets:
  runEslintTest:
    cmd: "gulp eslint-test"
    sh: true
```

The only problem i have is that the output is white text there is no color. I am missing a configuration? or simply it does not work this way?
