### ISSUE TITLE
yml custom build command error

### ISSUE THREAD

**Issue by aacirino** [noseglid/atom-build#559]
Hi, experimenting with atom-build I wrote the following yml file:

```yaml
cmd: ninja
name: build debug
cwd: "{PROJECT_PATH}/debug"
sh: false
targets:
  test:
    cmd: ninja
    args: test
```
When I try to execute the test target I get the following error:

`Failed to build. target.args.map is not a function`

If I try once more to run the test target I get this error:

`Failed to build. Status 'Build: Custom: test' is already set`

I can't see where the error is in yml file.

**Comment by noseglid** [comment]
`args` should be an array


```yaml
cmd: ninja
name: build debug
cwd: "{PROJECT_PATH}/debug"
sh: false
targets:
  test:
    cmd: ninja
    args:
      - test
```
